{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "hermes-engine",
    "version": "0.70.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.10-debug.aar",
          "url": "hermes-engine-0.70.10-debug.aar",
          "size": 4031737,
          "sha512": "daa83bfb6863fdac2236b466908903174a69bd9cbca0f5af2e287c440c74bc5385b24582815c8bd4df8de396c521defaa8a78cbd282f6bb633e16795b8c15e35",
          "sha256": "beee57a87676176835e341073995c4a3716623325d3b17082cbd8111fe113859",
          "sha1": "fb9ac97e6b3cef64e73eb151346dd2ed83b986c5",
          "md5": "f4df1777f787ffa9d70f8d7632e4f780"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.10-debug.aar",
          "url": "hermes-engine-0.70.10-debug.aar",
          "size": 4031737,
          "sha512": "daa83bfb6863fdac2236b466908903174a69bd9cbca0f5af2e287c440c74bc5385b24582815c8bd4df8de396c521defaa8a78cbd282f6bb633e16795b8c15e35",
          "sha256": "beee57a87676176835e341073995c4a3716623325d3b17082cbd8111fe113859",
          "sha1": "fb9ac97e6b3cef64e73eb151346dd2ed83b986c5",
          "md5": "f4df1777f787ffa9d70f8d7632e4f780"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.10-debug-sources.jar",
          "url": "hermes-engine-0.70.10-debug-sources.jar",
          "size": 62707,
          "sha512": "b6d659b87a103dd21026d8715420d047b70e76219d39121795598811cff2c7bb6cf3a860d8836fe6eeb753f785d7c2f7b961ea48c5cba27626a6e1cb5b07ee62",
          "sha256": "1fe6791aeefb0391d319d763c655a6f8232676141b886d0a467b8834a0b86497",
          "sha1": "75340c383a5d55a37d68181f12b1d8d939a3f065",
          "md5": "7b864274b543d21ee7d7c9c8e7f7b043"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.10-release.aar",
          "url": "hermes-engine-0.70.10-release.aar",
          "size": 3456774,
          "sha512": "7fe4f6d0dddfb2d10d3e5055e0cf37a79f53fe0c62bb8ead64b1270ae88f555fafc34c025253d44c5508cc2b44801b9c990aa49827542cb8f3b32a9747c13686",
          "sha256": "47971d77e012084ca5eb521c0a0c67a95befbc362b0697d729b7fd8a6423f46b",
          "sha1": "86becf8ba435348a9a0e28fba546a2b7c918bbf4",
          "md5": "7c9234add435afcc60b6b39cdf5f9995"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.10-release.aar",
          "url": "hermes-engine-0.70.10-release.aar",
          "size": 3456774,
          "sha512": "7fe4f6d0dddfb2d10d3e5055e0cf37a79f53fe0c62bb8ead64b1270ae88f555fafc34c025253d44c5508cc2b44801b9c990aa49827542cb8f3b32a9747c13686",
          "sha256": "47971d77e012084ca5eb521c0a0c67a95befbc362b0697d729b7fd8a6423f46b",
          "sha1": "86becf8ba435348a9a0e28fba546a2b7c918bbf4",
          "md5": "7c9234add435afcc60b6b39cdf5f9995"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.10-release-sources.jar",
          "url": "hermes-engine-0.70.10-release-sources.jar",
          "size": 62694,
          "sha512": "205a0fd395d6d02c27c4611ae1ceca7ccb4f3554f17f44d338f9ffef2e3521e933616e74ac1b17bb7d300891ede5ecf58e966a11becda27f6760f862f2316783",
          "sha256": "e622d9a7db5ba1a2161785ab8745dda58d1012aad04f7f9489fce207cf567f8a",
          "sha1": "34cf662170d553da87ddd8ef2213f13212955d1d",
          "md5": "c8db891c3be1b407d7079c02c303243b"
        }
      ]
    }
  ]
}
